param([switch]$VerifyOnly)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$patch = Join-Path $root 'patch'
$required = @(
  'winhttp.dll', '.doorstop_version', 'doorstop_config.ini', 'overTMP',
  'BepInEx/core/BepInEx.dll', 'BepInEx/core/BepInEx.Preloader.dll',
  'BepInEx/plugins/XUnity.AutoTranslator/XUnity.AutoTranslator.Plugin.BepInEx.dll',
  'BepInEx/plugins/XUnity.AutoTranslator/XUnity.AutoTranslator.Plugin.Core.dll',
  'BepInEx/plugins/XUnity.ResourceRedirector/XUnity.ResourceRedirector.dll',
  'BepInEx/unstripped/mscorlib.dll', 'BepInEx/unstripped/System.dll',
  'BepInEx/unstripped/UnityEngine.CoreModule.dll',
  'BepInEx/unstripped/Newtonsoft.Json.dll',
  'BepInEx/config/AutoTranslatorConfig.ini', 'BepInEx/Translation/zh/Text/ui.txt',
  'THIRD_PARTY_LICENSES/Newtonsoft.Json-LICENSE',
  'THIRD_PARTY_LICENSES/BepInEx-LICENSE', 'THIRD_PARTY_LICENSES/XUnity.AutoTranslator-LICENSE'
)
foreach ($relative in $required) {
  $path = Join-Path $patch $relative
  if (!(Test-Path -LiteralPath $path -PathType Leaf) -or (Get-Item -LiteralPath $path).Length -eq 0) { throw "Missing or empty: $relative" }
}
$files = @(Get-ChildItem -LiteralPath $patch -Recurse -File -Force)
$bad = @($files | Where-Object { $_.FullName -match 'PerformanceProbe|[\\/](debug|outputs|work|cache)[\\/]|\.log$|\.ps1$|_AutoGeneratedTranslations\.txt$' })
if ($bad.Count) { throw 'Debug or generated files found in patch/' }
$dll = Join-Path $patch 'BepInEx/unstripped/Newtonsoft.Json.dll'
if ((Get-FileHash -LiteralPath $dll -Algorithm SHA256).Hash -ne '7F02AEF8609D01C2EA8870FB4E6C6B6993C44988BE0697D7BD5A93681949AFE0') { throw 'JSON compatibility DLL hash mismatch' }
$cfg = [IO.File]::ReadAllText((Join-Path $patch 'BepInEx/config/AutoTranslatorConfig.ini'))
foreach ($setting in @('TextGetterCompatibilityMode=True','Endpoint=','FallbackEndpoint=','FallbackFontTextMeshPro=overTMP','Language=zh')) {
  if ($cfg -notmatch ('(?m)^' + [regex]::Escape($setting) + '\r?$')) { throw "Unexpected setting: $setting" }
}
foreach ($ini in $files | Where-Object { $_.Extension -in @('.ini','.cfg') }) {
  if ([IO.File]::ReadAllText($ini.FullName) -match '(?mi)^[ \t]*(ApiKey|AuthKey|Key|SecretKey|AccessToken|ClientSecret)[ \t]*=[ \t]*[^\s\r\n]') { throw 'Nonempty credential field in package configuration; value suppressed' }
}
$doorstop = [IO.File]::ReadAllText((Join-Path $patch 'doorstop_config.ini'))
if ($doorstop -notmatch '(?m)^dll_search_path_override\s*=\s*BepInEx\\unstripped\s*$') { throw 'Incorrect assembly search path' }
if ($doorstop -notmatch '(?m)^target_assembly\s*=\s*BepInEx\\core\\BepInEx.Preloader.dll\s*$') { throw 'Incorrect Mono loader path' }
$entries = @([IO.File]::ReadAllLines((Join-Path $patch 'BepInEx/Translation/zh/Text/ui.txt')) | Where-Object { $_.Trim() -and !$_.StartsWith('//') })
if ($entries.Count -lt 42661) { throw 'Translation file appears incomplete' }
Write-Host "Verified $($files.Count) package files; JSON fix, offline config and translation payload present."
if ($VerifyOnly) { return }
Add-Type -AssemblyName System.IO.Compression.FileSystem
$dist = Join-Path $root 'dist'
[IO.Directory]::CreateDirectory($dist) | Out-Null
$zip = Join-Path $dist 'SunlessSkies-Epic-CN.zip'
$tempZip = Join-Path $dist ('package-' + [guid]::NewGuid().ToString('N') + '.zip')
try {
  [IO.Compression.ZipFile]::CreateFromDirectory($patch, $tempZip)
  $archive = [IO.Compression.ZipFile]::OpenRead($tempZip)
  try {
    $zipped = @($archive.Entries | Where-Object { $_.Name })
    if ($zipped.Count -ne $files.Count) { throw 'ZIP file count mismatch' }
    foreach ($file in $files) {
      $relative = $file.FullName.Substring($patch.Length + 1).Replace('\','/')
      $entry = $archive.GetEntry($relative)
      if (!$entry) { $entry = $archive.GetEntry($relative.Replace('/','\')) }
      if (!$entry) { throw "ZIP missing: $relative" }
      $stream = $entry.Open()
      $sha = [Security.Cryptography.SHA256]::Create()
      try { $hash = [BitConverter]::ToString($sha.ComputeHash($stream)).Replace('-','') }
      finally { $stream.Dispose(); $sha.Dispose() }
      if ($hash -ne (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash) { throw "ZIP content mismatch: $relative" }
    }
  } finally { $archive.Dispose() }
  Move-Item -LiteralPath $tempZip -Destination $zip -Force
  Write-Host "Created and verified: $zip"
} finally {
  if (Test-Path -LiteralPath $tempZip) { Remove-Item -LiteralPath $tempZip }
}
